### ISSUE TITLE
Example app with embedded rocksdb

### ISSUE THREAD

**Issue by winding-lines** [spacejam/rust-rocksdb#34]
Thanks for putting together this library!

I've created an example app with an embedded rocksdb library:
https://github.com/winding-lines/rust-rocksdb-app

My intent is to be able to deploy the binary without requiring people to install rocksdb.

Let me know if you think this is useful :)

**Comment by spacejam** [comment]
Awesome!  This sort of thing is definitely useful, as it simplifies installation for many people.  I didn't want to be too opinionated about how people got the rocksdb library itself, which is why I didn't do this for the rust-rocksdb lib itself (a super early version had something similar but I took it out at the suggestion of some folks who had done more rust wrapper development at the time), but things like this and https://github.com/jsgf/rocksdb-sys can definitely save some people time.  Thanks for letting me know about this, and I'll definitely pass the word along about this if I hear about somebody looking for this sort of thing!

**Comment by winding-lines** [comment]
Great! Love your library so far, thanks for putting this together :-)

Marius
---
