### ISSUE TITLE
WriteBatch and Iterator Support

### ISSUE THREAD

**Issue by dgrnbrg** [spacejam/rust-rocksdb#9]
Hello, I'm very interested in adding support for these features. I've just started learning Rust, but I'd be happy to help if you could outline what it would take for me.

These features together add read and write transactions to the DB, which enables new use cases.

**Comment by spacejam** [comment]
You're halfway there!  Don't pick up too many bad habits from this codebase because it was also my first rust project and there's a good amount that needs to be cleaned up still :P Because creating an iterator in rocksdb essentially just records the offset of the tip of the LSM to scan backwards from during reads, it's safe and improves flexibility to decouple the returned iterator from the RocksDB object as much as possible.  

I'd maybe create a iter(&self) -> RocksDBIterator method on RocksDB, and implement the Iterator and DoubleEndedIterator traits for RocksDBIterator.  The RocksDBIterator doesn't need any state other than what RocksDB maintains for us on its end, so it can just be a repr(C) newtype wrapped by another object so that you can implement Drop without messing up the C interop, like what you did for WriteBatch. I'd avoid IntoIterator on RocksDB because into_iter(self) would consume the RocksDB object.

You may be able to override the last() method on Iterator such that it calls [rocksdb_iter_seek_to_last](https://github.com/facebook/rocksdb/blob/master/include/rocksdb/c.h#L398) and then returns the element if rocksdb_iter_valid is true.  Note that last has a signature of last(self), meaning that self will be consumed by the call to this method, so we don't need to store any previous state or anything like that.

You seem to be picking this up pretty quickly, but let me know here or via email (on profile) or hangouts if you have any questions, and I'd be happy to teach you what I know.

**Comment by dgrnbrg** [comment]
I've mostly implemented iterators here: dgrnbrg/rust-rocksdb@b491d27 which still needs more cleanup and testing. It does, however, support snapshots, memory safety, and doesn't allocate when traversing the iterator.

I'd like to add support for snapshots as well, and then I'll drop in a PR. I think that it's time to put the tests into a separate project--do you have a good example of how I can make dedicated files for tests, to shorten & simplify the code?

Thanks!

**Comment by spacejam** [comment]
Awesome, I'm really looking forward to this!  I find that I often look at Carl Lerche's code when I'm interested in finding a nice example for how to do something.  Does the way that some testing is pulled into a separate module [here](https://github.com/carllerche/mio) fit the bill?  Note that there are still inline tests (search for #[cfg(test)]) for certain tests but much of it has been separated.

**Comment by spacejam** [comment]
This has landed and is now available in crate version 0.0.7, thanks @dgrnbrg!
